from typing import List
"""Insert into test.py or scatter.py, whatever the python file is called."""

# URL_list: List[str] = ['https://raw.githubusercontent.com/Carolina-Data-Challenge/datasets/main/FootballDatasets/NFL/RegSeason/nfl1978lines.csv', 
# 'https://raw.githubusercontent.com/Carolina-Data-Challenge/datasets/main/FootballDatasets/NFL/RegSeason/nfl1979lines.csv', 
# 'https://raw.githubusercontent.com/Carolina-Data-Challenge/datasets/main/FootballDatasets/NFL/RegSeason/nfl1980lines.csv',
# 'https://raw.githubusercontent.com/Carolina-Data-Challenge/datasets/main/FootballDatasets/NFL/RegSeason/nfl1981lines.csv',
# 'https://raw.githubusercontent.com/Carolina-Data-Challenge/datasets/main/FootballDatasets/NFL/RegSeason/nfl1983lines.csv',
# 'https://raw.githubusercontent.com/Carolina-Data-Challenge/datasets/main/FootballDatasets/NFL/RegSeason/nfl1982lines.csv',
# 'https://raw.githubusercontent.com/Carolina-Data-Challenge/datasets/main/FootballDatasets/NFL/RegSeason/nfl1984lines.csv',
# 'https://raw.githubusercontent.com/Carolina-Data-Challenge/datasets/main/FootballDatasets/NFL/RegSeason/nfl1985lines.csv',
# 'https://raw.githubusercontent.com/Carolina-Data-Challenge/datasets/main/FootballDatasets/NFL/RegSeason/nfl1986lines.csv',
# 'https://raw.githubusercontent.com/Carolina-Data-Challenge/datasets/main/FootballDatasets/NFL/RegSeason/nfl1987lines.csv',
# 'https://raw.githubusercontent.com/Carolina-Data-Challenge/datasets/main/FootballDatasets/NFL/RegSeason/nfl1988lines.csv',
# 'https://raw.githubusercontent.com/Carolina-Data-Challenge/datasets/main/FootballDatasets/NFL/RegSeason/nfl1989lines.csv',
# 'https://raw.githubusercontent.com/Carolina-Data-Challenge/datasets/main/FootballDatasets/NFL/RegSeason/nfl1990lines.csv',
# 'https://raw.githubusercontent.com/Carolina-Data-Challenge/datasets/main/FootballDatasets/NFL/RegSeason/nfl1991lines.csv',
# 'https://raw.githubusercontent.com/Carolina-Data-Challenge/datasets/main/FootballDatasets/NFL/RegSeason/nfl1992lines.csv',
# 'https://raw.githubusercontent.com/Carolina-Data-Challenge/datasets/main/FootballDatasets/NFL/RegSeason/nfl1993lines.csv',
# 'https://raw.githubusercontent.com/Carolina-Data-Challenge/datasets/main/FootballDatasets/NFL/RegSeason/nfl1994lines.csv',
URL_list: List[str] = ['https://raw.githubusercontent.com/Carolina-Data-Challenge/datasets/main/FootballDatasets/NFL/RegSeason/nfl1995lines.csv',
'https://raw.githubusercontent.com/Carolina-Data-Challenge/datasets/main/FootballDatasets/NFL/RegSeason/nfl1996lines.csv',
'https://raw.githubusercontent.com/Carolina-Data-Challenge/datasets/main/FootballDatasets/NFL/RegSeason/nfl1997lines.csv',
'https://raw.githubusercontent.com/Carolina-Data-Challenge/datasets/main/FootballDatasets/NFL/RegSeason/nfl1998lines.csv',
'https://raw.githubusercontent.com/Carolina-Data-Challenge/datasets/main/FootballDatasets/NFL/RegSeason/nfl1999lines.csv',
'https://raw.githubusercontent.com/Carolina-Data-Challenge/datasets/main/FootballDatasets/NFL/RegSeason/nfl2000lines.csv',
'https://raw.githubusercontent.com/Carolina-Data-Challenge/datasets/main/FootballDatasets/NFL/RegSeason/nfl2001lines.csv',
'https://raw.githubusercontent.com/Carolina-Data-Challenge/datasets/main/FootballDatasets/NFL/RegSeason/nfl2002lines.csv',
'https://raw.githubusercontent.com/Carolina-Data-Challenge/datasets/main/FootballDatasets/NFL/RegSeason/nfl2003lines.csv', #from here i just modified links by changing year so if it fails replace links after this
'https://raw.githubusercontent.com/Carolina-Data-Challenge/datasets/main/FootballDatasets/NFL/RegSeason/nfl2004lines.csv',
'https://raw.githubusercontent.com/Carolina-Data-Challenge/datasets/main/FootballDatasets/NFL/RegSeason/nfl2005lines.csv',
'https://raw.githubusercontent.com/Carolina-Data-Challenge/datasets/main/FootballDatasets/NFL/RegSeason/nfl2006lines.csv',
'https://raw.githubusercontent.com/Carolina-Data-Challenge/datasets/main/FootballDatasets/NFL/RegSeason/nfl2007lines.csv',
'https://raw.githubusercontent.com/Carolina-Data-Challenge/datasets/main/FootballDatasets/NFL/RegSeason/nfl2008lines.csv',
'https://raw.githubusercontent.com/Carolina-Data-Challenge/datasets/main/FootballDatasets/NFL/RegSeason/nfl2009lines.csv',
'https://raw.githubusercontent.com/Carolina-Data-Challenge/datasets/main/FootballDatasets/NFL/RegSeason/nfl2010lines.csv',
'https://raw.githubusercontent.com/Carolina-Data-Challenge/datasets/main/FootballDatasets/NFL/RegSeason/nfl2011lines.csv',
'https://raw.githubusercontent.com/Carolina-Data-Challenge/datasets/main/FootballDatasets/NFL/RegSeason/nfl2012lines.csv',
'https://raw.githubusercontent.com/Carolina-Data-Challenge/datasets/main/FootballDatasets/NFL/RegSeason/nfl2013lines.csv'
]